[package]
name = "lyra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.67"
dotenv = "0.15.0"
hex = "0.4.3"
anyhow = "1.0.70"
tokio = { version = "1.26.0", features = ["full"] }
hyper = { version = "0.14.25", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde_json = "1.0.94"
rand = "0.8.5"
rand_chacha = "0.3.1"
itertools = "0.10.5"
rayon = "1.7.0"
cached = "0.42.0"
once_cell = "1.17.1"
chrono = "0.4.24"
convert_case = "0.6.0"

twilight = "0.15.0"
twilight-cache-inmemory = "0.15.1"
twilight-gateway = "0.15.1"
twilight-http = "0.15.1"
twilight-model = "0.15.1"
twilight-standby = "0.15.1"
twilight-util = { version = "0.15.1", features = ["builder"] }
twilight-lavalink = "0.15.1"
twilight-interactions = "0.15.0"

lyra_proc = { path = "./lyra_proc" }

[dependencies.kmeans_colors]
version = "0.5.0"
features = ["palette_color"]
default-features = false

[dependencies.image]
version = "0.24.5"
features = ["jpeg", "png", "gif", "tiff"]
default-features = false

[dependencies.palette]
version = "0.6.1"
features = ["std"]
default-features = false
