[package]
name = "lyra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
hex = "0.4.3"
anyhow = "1.0.69"
tokio = { version = "1.25.0", features = ["full"] }
hyper = { version = "0.14.24", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde_json = "1.0.93"
rand = "0.8.5"
rand_chacha = "0.3.1"
itertools = "0.10.5"
rayon = "1.6.1"
cached = "0.42.0"
ed25519-dalek = "1.0.1"
once_cell = "1.17.1"

twilight = "0.15.0"
twilight-cache-inmemory = "0.15.0"
twilight-gateway = "0.15.0"
twilight-http = "0.15.0"
twilight-model = "0.15.0"
twilight-standby = "0.15.0"
twilight-lavalink = "0.15.0"
twilight-interactions = "0.15.0"

[dependencies.kmeans_colors]
version = "0.5.0"
features = ["palette_color"]
default-features = false

[dependencies.image]
version = "0.24.5"
features = ["jpeg", "png", "gif", "tiff"]
default-features = false

[dependencies.palette]
version = "0.6.1"
features = ["std"]
default-features = false
